import { Roboto } from "next/font/google";
import "./globals.css";

// Components
import MainNavbar from "./components/Navbar"

const roboto = Roboto({
  weight: '500',
  subsets: ['latin'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className} suppressHydrationWarning={true}>
        <MainNavbar />
        {children}
      </body>
    </html>
  );
}
